name: Deploy Backend Laravel

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "app/,bootstrap/,config/,database/,public/,resources/,routes/,nginx/,artisan,composer.json,composer.lock,docker-compose.yml,Dockerfile"
          target: "/root/my-app"

      - name: Update Dependencies & Run Artisan Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/my-app

            # 1. Matikan queue sementara agar tidak crash saat folder vendor diubah
            docker compose stop queue

            # 2. Hapus semua cache lama agar tidak crash saat booting setelah pergantian package
            docker compose exec -T app rm -f bootstrap/cache/*.php

            # 3. Install dependency untuk production
            docker compose exec -T app env COMPOSER_MEMORY_LIMIT=-1 composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

            # 4. Migrate database
            docker compose exec -T app php artisan migrate --force

            # 5. Clear & Re-cache
            docker compose exec -T app php artisan optimize:clear
            docker compose exec -T app php artisan config:cache
            docker compose exec -T app php artisan route:cache
            docker compose exec -T app php artisan view:cache

            # 6. Nyalakan queue kembali setelah deploy selesai
            docker compose start queue
